# Generated by Django 3.0.8 on 2020-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_archivejournal_awards_doaevents_doanews_pastmembers_pastofficebearers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivejournal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doaevents',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doanews',
            name='description',
            field=models.TextField(),
        ),
    ]
