# Generated by Django 3.0.8 on 2020-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200713_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doaevents',
            name='emonth',
            field=models.CharField(choices=[('January', 'January'), ('feburary', 'feburary'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], max_length=20, null=True),
        ),
    ]
