# Generated by Django 3.0.8 on 2020-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200713_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doaevents',
            name='efile',
            field=models.FileField(blank=True, null=True, upload_to='eventfile'),
        ),
    ]
