# Generated by Django 3.0.8 on 2020-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200713_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membertype', models.CharField(choices=[('lifetime', 'Lifetime Member'), ('associate', 'Associate Member')], max_length=200)),
                ('memberfees', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('postaddress', models.CharField(max_length=555)),
                ('peraddress', models.CharField(max_length=555)),
                ('state', models.CharField(max_length=355)),
                ('pincode', models.IntegerField(null=True)),
                ('study', models.CharField(max_length=555)),
                ('institute', models.CharField(max_length=355)),
                ('interest', models.CharField(max_length=555)),
                ('extrainterest', models.CharField(max_length=355)),
                ('hospital', models.CharField(max_length=555)),
                ('position', models.CharField(max_length=255)),
                ('clinicaddress', models.CharField(max_length=555)),
                ('contactno', models.IntegerField(null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('paymenttype', models.CharField(max_length=200)),
                ('paymentscreen', models.FileField(upload_to='members')),
                ('degreescreen', models.FileField(upload_to='members')),
                ('certificatecreen', models.FileField(upload_to='members')),
            ],
        ),
        migrations.AlterField(
            model_name='doaevents',
            name='emonth',
            field=models.CharField(choices=[('January', 'January'), ('Feburary', 'Feburary'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True),
        ),
    ]
