# Generated by Django 3.0.8 on 2020-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200715_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='awardfile',
            field=models.FileField(blank=True, null=True, upload_to='awards'),
        ),
    ]
