# Generated by Django 3.0.8 on 2020-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_newmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='paymentscreen',
            field=models.FileField(default=True, upload_to='members'),
            preserve_default=False,
        ),
    ]
