# Generated by Django 3.0.8 on 2020-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200718_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slidertitle', models.CharField(max_length=225)),
                ('slider', models.FileField(upload_to='slider')),
                ('sliderlink', models.CharField(max_length=225)),
            ],
        ),
    ]
