# Generated by Django 3.0.8 on 2020-07-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200724_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='memberid',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
