# Generated by Django 3.0.8 on 2020-07-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200726_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='email',
        ),
        migrations.RemoveField(
            model_name='members',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='members',
            name='memberid',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
    ]
