# Generated by Django 3.0.8 on 2020-07-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_members_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='firstname',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
