# Generated by Django 3.0.8 on 2020-07-26 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0024_members_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='members',
            name='user',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
