# Generated by Django 3.0.8 on 2020-07-27 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200726_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doaevents',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='sliderlink',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
