# Generated by Django 3.0.8 on 2020-07-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20200727_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='sliderlink',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
