# Generated by Django 3.0.8 on 2020-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200727_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='homeclass',
            field=models.CharField(blank=True, choices=[('', ''), ('active', 'active')], max_length=200, null=True),
        ),
    ]
